<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="XiongBeauty" ignored="0" name="test1" tests="4" failures="2" timestamp="2020-11-16T09:32:15 CST" time="6.478" errors="0">
  <testcase name="test1" time="0.011" classname="com.webtest.demo.Admin_Login"/>
  <testcase name="test2" time="0.004" classname="com.webtest.demo.Admin_Login">
    <failure type="java.lang.AssertionError" message="expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [5] but found [3]
at com.webtest.demo.Admin_Login.test2(Admin_Login.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="com.webtest.demo.Admin_Login">
    <failure type="java.lang.AssertionError" message="expected [6] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [7]
at com.webtest.demo.Admin_Login.test3(Admin_Login.java:39)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="com.webtest.demo.Admin_Login"/>
</testsuite> <!-- test1 -->
