<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14233" started-at="2020-11-10T08:08:32 CST" finished-at="2020-11-10T08:08:46 CST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14233" started-at="2020-11-10T08:08:32 CST" finished-at="2020-11-10T08:08:46 CST">
      <class name="com.webtest.demo.Admin_Login">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:com.webtest.demo.Admin_Login@32709393]" name="doBeforeClass" is-config="true" duration-ms="4318" started-at="2020-11-10T08:08:32 CST" finished-at="2020-11-10T08:08:36 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="FAIL" signature="test5()[pri:0, instance:com.webtest.demo.Admin_Login@32709393]" name="test5" duration-ms="8" started-at="2020-11-10T08:08:36 CST" finished-at="2020-11-10T08:08:36 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [4] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [4] but found [1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.webtest.demo.Admin_Login.test5(Admin_Login.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:com.webtest.demo.Admin_Login@32709393]" name="testLogin" duration-ms="8682" started-at="2020-11-10T08:08:36 CST" finished-at="2020-11-10T08:08:45 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:com.webtest.demo.Admin_Login@32709393]" name="doAfterMethod" is-config="true" duration-ms="1196" started-at="2020-11-10T08:08:45 CST" finished-at="2020-11-10T08:08:46 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
        <test-method status="PASS" signature="mailUtil()[pri:0, instance:com.webtest.demo.Admin_Login@32709393]" name="mailUtil" is-config="true" duration-ms="2451" started-at="2020-11-10T08:08:46 CST" finished-at="2020-11-10T08:08:49 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mailUtil -->
      </class> <!-- com.webtest.demo.Admin_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
